import '../data/models/track.dart';

final List<Track> mockTracks = [
  Track(
    id: 1,
    name: "Rock Helix",
    artistId: "The Tides",
    images: ["https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 2,
    name: "Ocean Waves",
    artistId: "The Tides",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 3,
    name: "Electric Pulse",
    artistId: "Neon Knights",
    images: ["https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 4,
    name: "Summer Breeze",
    artistId: "Coastal Vibes",
    images: ["https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 5,
    name: "City Lights",
    artistId: "Urban Echo",
    images: ["https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 6,
    name: "Mountain High",
    artistId: "Alpine Sound",
    images: ["https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 7,
    name: "Starlight",
    artistId: "Cosmic Journey",
    images: ["https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 8,
    name: "Desert Storm",
    artistId: "Sand Dunes",
    images: ["https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 9,
    name: "Neon Nights",
    artistId: "Retro Wave",
    images: ["https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    createdAt: DateTime.now(),
  ),
  Track(
    id: 10,
    name: "Rainforest",
    artistId: "Nature's Symphony",
    images: ["https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400"],
    uri: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    createdAt: DateTime.now(),
  ),
];

final List<String> genres = [
  "Pop",
  "Rock",
  "Jazz",
  "Classical",
  "Hip-Hop",
  "Electronic",
  "Country",
  "Reggae",
  "Blues",
  "Folk",
];
